// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  TechcorWebApiDesignControllerUpdateData,
  TechcorWebApiDesignControllerUpdateErrors,
  TechcorWebApiDesignControllerUpdateResponses,
  TechcorWebApiImplementationsControllerCreateData,
  TechcorWebApiImplementationsControllerCreateErrors,
  TechcorWebApiImplementationsControllerCreateResponses,
  TechcorWebApiOpenApiControllerSpecData,
  TechcorWebApiOpenApiControllerSpecResponses,
  TechcorWebApiOrganizationsControllerShowData,
  TechcorWebApiOrganizationsControllerShowErrors,
  TechcorWebApiOrganizationsControllerShowResponses,
  TechcorWebApiProjectsControllerCreateData,
  TechcorWebApiProjectsControllerCreateErrors,
  TechcorWebApiProjectsControllerCreateResponses,
  TechcorWebApiProjectsControllerIndexData,
  TechcorWebApiProjectsControllerIndexErrors,
  TechcorWebApiProjectsControllerIndexResponses,
  TechcorWebApiProjectsControllerShowData,
  TechcorWebApiProjectsControllerShowErrors,
  TechcorWebApiProjectsControllerShowResponses,
  TechcorWebApiRequirementsControllerAcceptData,
  TechcorWebApiRequirementsControllerAcceptErrors,
  TechcorWebApiRequirementsControllerAcceptResponses,
  TechcorWebApiRequirementsControllerCreateData,
  TechcorWebApiRequirementsControllerCreateErrors,
  TechcorWebApiRequirementsControllerCreateResponses,
  TechcorWebApiRequirementsControllerIndexData,
  TechcorWebApiRequirementsControllerIndexErrors,
  TechcorWebApiRequirementsControllerIndexResponses,
  TechcorWebApiRequirementsControllerShowData,
  TechcorWebApiRequirementsControllerShowErrors,
  TechcorWebApiRequirementsControllerShowResponses,
  TechcorWebApiRequirementsControllerUpdateData,
  TechcorWebApiRequirementsControllerUpdateErrors,
  TechcorWebApiRequirementsControllerUpdateResponses,
  TechcorWebApiTasksControllerIndexData,
  TechcorWebApiTasksControllerIndexErrors,
  TechcorWebApiTasksControllerIndexResponses,
  TechcorWebApiTasksControllerShowData,
  TechcorWebApiTasksControllerShowErrors,
  TechcorWebApiTasksControllerShowResponses,
  TechcorWebApiTasksControllerVerifyData,
  TechcorWebApiTasksControllerVerifyErrors,
  TechcorWebApiTasksControllerVerifyResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * OpenAPI specification
 *
 * Returns the OpenAPI 3.0 specification for the Technically Correct API.
 */
export const techcorWebApiOpenApiControllerSpec = <ThrowOnError extends boolean = false>(
  options?: Options<TechcorWebApiOpenApiControllerSpecData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    TechcorWebApiOpenApiControllerSpecResponses,
    unknown,
    ThrowOnError
  >({ url: "/api/openapi.json", ...options });

/**
 * Get organization
 *
 * Returns the organization associated with the bearer token.
 */
export const techcorWebApiOrganizationsControllerShow = <ThrowOnError extends boolean = false>(
  options?: Options<TechcorWebApiOrganizationsControllerShowData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    TechcorWebApiOrganizationsControllerShowResponses,
    TechcorWebApiOrganizationsControllerShowErrors,
    ThrowOnError
  >({ url: "/api/v1/org", ...options });

/**
 * List projects
 *
 * Returns all active projects for the organization.
 */
export const techcorWebApiProjectsControllerIndex = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiProjectsControllerIndexData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiProjectsControllerIndexResponses,
    TechcorWebApiProjectsControllerIndexErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/projects", ...options });

/**
 * Create a project
 *
 * Creates a new project under the organization.
 */
export const techcorWebApiProjectsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiProjectsControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TechcorWebApiProjectsControllerCreateResponses,
    TechcorWebApiProjectsControllerCreateErrors,
    ThrowOnError
  >({
    url: "/api/v1/{org_slug}/projects",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get a project
 *
 * Returns a single project by slug.
 */
export const techcorWebApiProjectsControllerShow = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiProjectsControllerShowData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiProjectsControllerShowResponses,
    TechcorWebApiProjectsControllerShowErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}", ...options });

/**
 * List requirements
 *
 * Returns all active requirements for a project.
 */
export const techcorWebApiRequirementsControllerIndex = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiRequirementsControllerIndexData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiRequirementsControllerIndexResponses,
    TechcorWebApiRequirementsControllerIndexErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/requirements", ...options });

/**
 * Create requirement
 *
 * Creates a requirement and enqueues the AI pipeline. Returns a task to poll.
 */
export const techcorWebApiRequirementsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiRequirementsControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TechcorWebApiRequirementsControllerCreateResponses,
    TechcorWebApiRequirementsControllerCreateErrors,
    ThrowOnError
  >({
    url: "/api/v1/{org_slug}/{project_slug}/requirements",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get requirement
 *
 * Returns a single requirement by identifier.
 */
export const techcorWebApiRequirementsControllerShow = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiRequirementsControllerShowData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiRequirementsControllerShowResponses,
    TechcorWebApiRequirementsControllerShowErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}", ...options });

/**
 * Edit requirement
 *
 * Edits a requirement's text and/or parent. Text changes enqueue the AI pipeline. Parent changes are synchronous and return the updated requirement. At least one of `text` or `parent_identifier` is required.
 */
export const techcorWebApiRequirementsControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiRequirementsControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    TechcorWebApiRequirementsControllerUpdateResponses,
    TechcorWebApiRequirementsControllerUpdateErrors,
    ThrowOnError
  >({
    url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Accept requirement
 *
 * Accepts a requirement and completes any pending acceptance task.
 */
export const techcorWebApiRequirementsControllerAccept = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiRequirementsControllerAcceptData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TechcorWebApiRequirementsControllerAcceptResponses,
    TechcorWebApiRequirementsControllerAcceptErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/accept", ...options });

/**
 * Update design
 *
 * Creates or updates the design for a requirement. Always creates a new version.
 */
export const techcorWebApiDesignControllerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiDesignControllerUpdateData, ThrowOnError>
) =>
  (options.client ?? client).put<
    TechcorWebApiDesignControllerUpdateResponses,
    TechcorWebApiDesignControllerUpdateErrors,
    ThrowOnError
  >({
    url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/design",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create implementation
 *
 * Creates an implementation node linked to a requirement via a realized-by edge. Auto-creates a placeholder design if the requirement has none.
 */
export const techcorWebApiImplementationsControllerCreate = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiImplementationsControllerCreateData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TechcorWebApiImplementationsControllerCreateResponses,
    TechcorWebApiImplementationsControllerCreateErrors,
    ThrowOnError
  >({
    url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/implementations",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * List active tasks
 *
 * Returns active tasks for a project, descending by creation time.
 */
export const techcorWebApiTasksControllerIndex = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiTasksControllerIndexData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiTasksControllerIndexResponses,
    TechcorWebApiTasksControllerIndexErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/tasks", ...options });

/**
 * Get task
 *
 * Returns a single task by ID. Poll until status is complete or failed.
 */
export const techcorWebApiTasksControllerShow = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiTasksControllerShowData, ThrowOnError>
) =>
  (options.client ?? client).get<
    TechcorWebApiTasksControllerShowResponses,
    TechcorWebApiTasksControllerShowErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/tasks/{id}", ...options });

/**
 * Verify task
 *
 * Accepts the requirement and completes the task. No-op if task is not awaiting_review.
 */
export const techcorWebApiTasksControllerVerify = <ThrowOnError extends boolean = false>(
  options: Options<TechcorWebApiTasksControllerVerifyData, ThrowOnError>
) =>
  (options.client ?? client).post<
    TechcorWebApiTasksControllerVerifyResponses,
    TechcorWebApiTasksControllerVerifyErrors,
    ThrowOnError
  >({ url: "/api/v1/{org_slug}/{project_slug}/tasks/{id}/verify", ...options });
