// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}/api/v1` | (string & {});
};

/**
 * Design
 */
export type Design = {
  inserted_at: string;
  requirement_url: string;
  status: string;
  text: string;
  update_url: string;
};

/**
 * DesignUpdate
 */
export type DesignUpdate = {
  text: string;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
  error: string;
};

/**
 * Implementation
 */
export type Implementation = {
  commit_hash: string;
  commit_message: string;
  description?: string | null;
  identifier: string;
  inserted_at: string;
  repo: string;
  requirement_url: string;
  status: string;
  text: string;
  updated_at: string;
};

/**
 * ImplementationCreate
 */
export type ImplementationCreate = {
  commit_hash: string;
  commit_message: string;
  description?: string | null;
  repo: string;
};

/**
 * Organization
 */
export type Organization = {
  inserted_at: string;
  name: string;
  projects_url: string;
  slug: string;
  url: string;
};

/**
 * Project
 */
export type Project = {
  description?: string | null;
  id: number;
  inserted_at: string;
  name: string;
  requirements_url: string;
  slug: string;
  tasks_url: string;
  url: string;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
  description?: string | null;
  name: string;
};

/**
 * ProjectList
 */
export type ProjectList = {
  data: Array<Project>;
};

/**
 * Requirement
 */
export type Requirement = {
  context?: string | null;
  id: number;
  identifier: string;
  inserted_at: string;
  status: "accepted" | "updated" | "rejected";
  text: string;
  url: string;
};

/**
 * RequirementCreate
 */
export type RequirementCreate = {
  context?: string | null;
  parent_identifier?: string | null;
  text: string;
};

/**
 * RequirementList
 */
export type RequirementList = {
  data: Array<Requirement>;
};

/**
 * RequirementUpdate
 */
export type RequirementUpdate = {
  context?: string | null;
  text: string;
};

/**
 * Task
 */
export type Task = {
  error?: string | null;
  id: number;
  inserted_at: string;
  result?: {
    [key: string]: unknown;
  } | null;
  status: "in_progress" | "awaiting_review" | "complete" | "failed";
  type: string;
  url: string;
};

/**
 * TaskList
 */
export type TaskList = {
  data: Array<Task>;
};

export type TechcorWebApiOpenApiControllerSpecData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/openapi.json";
};

export type TechcorWebApiOpenApiControllerSpecResponses = {
  /**
   * OpenAPI spec
   */
  200: {
    [key: string]: unknown;
  };
};

export type TechcorWebApiOpenApiControllerSpecResponse =
  TechcorWebApiOpenApiControllerSpecResponses[keyof TechcorWebApiOpenApiControllerSpecResponses];

export type TechcorWebApiOrganizationsControllerShowData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/org";
};

export type TechcorWebApiOrganizationsControllerShowErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
};

export type TechcorWebApiOrganizationsControllerShowError =
  TechcorWebApiOrganizationsControllerShowErrors[keyof TechcorWebApiOrganizationsControllerShowErrors];

export type TechcorWebApiOrganizationsControllerShowResponses = {
  /**
   * Organization
   */
  200: Organization;
};

export type TechcorWebApiOrganizationsControllerShowResponse =
  TechcorWebApiOrganizationsControllerShowResponses[keyof TechcorWebApiOrganizationsControllerShowResponses];

export type TechcorWebApiProjectsControllerIndexData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/projects";
};

export type TechcorWebApiProjectsControllerIndexErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiProjectsControllerIndexError =
  TechcorWebApiProjectsControllerIndexErrors[keyof TechcorWebApiProjectsControllerIndexErrors];

export type TechcorWebApiProjectsControllerIndexResponses = {
  /**
   * Project list
   */
  200: ProjectList;
};

export type TechcorWebApiProjectsControllerIndexResponse =
  TechcorWebApiProjectsControllerIndexResponses[keyof TechcorWebApiProjectsControllerIndexResponses];

export type TechcorWebApiProjectsControllerCreateData = {
  /**
   * Project params
   */
  body: ProjectCreate;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/projects";
};

export type TechcorWebApiProjectsControllerCreateErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
  /**
   * Validation error
   */
  422: ErrorResponse;
};

export type TechcorWebApiProjectsControllerCreateError =
  TechcorWebApiProjectsControllerCreateErrors[keyof TechcorWebApiProjectsControllerCreateErrors];

export type TechcorWebApiProjectsControllerCreateResponses = {
  /**
   * Created project
   */
  201: Project;
};

export type TechcorWebApiProjectsControllerCreateResponse =
  TechcorWebApiProjectsControllerCreateResponses[keyof TechcorWebApiProjectsControllerCreateResponses];

export type TechcorWebApiProjectsControllerShowData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}";
};

export type TechcorWebApiProjectsControllerShowErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiProjectsControllerShowError =
  TechcorWebApiProjectsControllerShowErrors[keyof TechcorWebApiProjectsControllerShowErrors];

export type TechcorWebApiProjectsControllerShowResponses = {
  /**
   * Project
   */
  200: Project;
};

export type TechcorWebApiProjectsControllerShowResponse =
  TechcorWebApiProjectsControllerShowResponses[keyof TechcorWebApiProjectsControllerShowResponses];

export type TechcorWebApiRequirementsControllerIndexData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements";
};

export type TechcorWebApiRequirementsControllerIndexErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiRequirementsControllerIndexError =
  TechcorWebApiRequirementsControllerIndexErrors[keyof TechcorWebApiRequirementsControllerIndexErrors];

export type TechcorWebApiRequirementsControllerIndexResponses = {
  /**
   * Requirement list
   */
  200: RequirementList;
};

export type TechcorWebApiRequirementsControllerIndexResponse =
  TechcorWebApiRequirementsControllerIndexResponses[keyof TechcorWebApiRequirementsControllerIndexResponses];

export type TechcorWebApiRequirementsControllerCreateData = {
  /**
   * Requirement params
   */
  body: RequirementCreate;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements";
};

export type TechcorWebApiRequirementsControllerCreateErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
  /**
   * Validation error
   */
  422: ErrorResponse;
};

export type TechcorWebApiRequirementsControllerCreateError =
  TechcorWebApiRequirementsControllerCreateErrors[keyof TechcorWebApiRequirementsControllerCreateErrors];

export type TechcorWebApiRequirementsControllerCreateResponses = {
  /**
   * Task
   */
  202: Task;
};

export type TechcorWebApiRequirementsControllerCreateResponse =
  TechcorWebApiRequirementsControllerCreateResponses[keyof TechcorWebApiRequirementsControllerCreateResponses];

export type TechcorWebApiRequirementsControllerShowData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Requirement identifier (e.g. 1.0, 1.1.2)
     */
    identifier: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}";
};

export type TechcorWebApiRequirementsControllerShowErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiRequirementsControllerShowError =
  TechcorWebApiRequirementsControllerShowErrors[keyof TechcorWebApiRequirementsControllerShowErrors];

export type TechcorWebApiRequirementsControllerShowResponses = {
  /**
   * Requirement
   */
  200: Requirement;
};

export type TechcorWebApiRequirementsControllerShowResponse =
  TechcorWebApiRequirementsControllerShowResponses[keyof TechcorWebApiRequirementsControllerShowResponses];

export type TechcorWebApiRequirementsControllerUpdateData = {
  /**
   * Requirement edit params
   */
  body: RequirementUpdate;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Requirement identifier (e.g. 1.0, 1.1.2)
     */
    identifier: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}";
};

export type TechcorWebApiRequirementsControllerUpdateErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
  /**
   * Validation error
   */
  422: ErrorResponse;
};

export type TechcorWebApiRequirementsControllerUpdateError =
  TechcorWebApiRequirementsControllerUpdateErrors[keyof TechcorWebApiRequirementsControllerUpdateErrors];

export type TechcorWebApiRequirementsControllerUpdateResponses = {
  /**
   * Task
   */
  202: Task;
};

export type TechcorWebApiRequirementsControllerUpdateResponse =
  TechcorWebApiRequirementsControllerUpdateResponses[keyof TechcorWebApiRequirementsControllerUpdateResponses];

export type TechcorWebApiRequirementsControllerAcceptData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Requirement identifier (e.g. 1.0, 1.1.2)
     */
    identifier: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/accept";
};

export type TechcorWebApiRequirementsControllerAcceptErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiRequirementsControllerAcceptError =
  TechcorWebApiRequirementsControllerAcceptErrors[keyof TechcorWebApiRequirementsControllerAcceptErrors];

export type TechcorWebApiRequirementsControllerAcceptResponses = {
  /**
   * Requirement
   */
  200: Requirement;
};

export type TechcorWebApiRequirementsControllerAcceptResponse =
  TechcorWebApiRequirementsControllerAcceptResponses[keyof TechcorWebApiRequirementsControllerAcceptResponses];

export type TechcorWebApiDesignControllerUpdateData = {
  /**
   * Design params
   */
  body: DesignUpdate;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Requirement identifier (e.g. 1.0, 1.1.2)
     */
    identifier: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/design";
};

export type TechcorWebApiDesignControllerUpdateErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
  /**
   * Validation error
   */
  422: ErrorResponse;
};

export type TechcorWebApiDesignControllerUpdateError =
  TechcorWebApiDesignControllerUpdateErrors[keyof TechcorWebApiDesignControllerUpdateErrors];

export type TechcorWebApiDesignControllerUpdateResponses = {
  /**
   * Design
   */
  200: Design;
};

export type TechcorWebApiDesignControllerUpdateResponse =
  TechcorWebApiDesignControllerUpdateResponses[keyof TechcorWebApiDesignControllerUpdateResponses];

export type TechcorWebApiImplementationsControllerCreateData = {
  /**
   * Implementation params
   */
  body: ImplementationCreate;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Requirement identifier (e.g. 1.0, 1.1.2)
     */
    identifier: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/requirements/{identifier}/implementations";
};

export type TechcorWebApiImplementationsControllerCreateErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
  /**
   * Validation error
   */
  422: ErrorResponse;
};

export type TechcorWebApiImplementationsControllerCreateError =
  TechcorWebApiImplementationsControllerCreateErrors[keyof TechcorWebApiImplementationsControllerCreateErrors];

export type TechcorWebApiImplementationsControllerCreateResponses = {
  /**
   * Implementation
   */
  201: Implementation;
};

export type TechcorWebApiImplementationsControllerCreateResponse =
  TechcorWebApiImplementationsControllerCreateResponses[keyof TechcorWebApiImplementationsControllerCreateResponses];

export type TechcorWebApiTasksControllerIndexData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/tasks";
};

export type TechcorWebApiTasksControllerIndexErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiTasksControllerIndexError =
  TechcorWebApiTasksControllerIndexErrors[keyof TechcorWebApiTasksControllerIndexErrors];

export type TechcorWebApiTasksControllerIndexResponses = {
  /**
   * Task list
   */
  200: TaskList;
};

export type TechcorWebApiTasksControllerIndexResponse =
  TechcorWebApiTasksControllerIndexResponses[keyof TechcorWebApiTasksControllerIndexResponses];

export type TechcorWebApiTasksControllerShowData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Task ID
     */
    id: number;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/tasks/{id}";
};

export type TechcorWebApiTasksControllerShowErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiTasksControllerShowError =
  TechcorWebApiTasksControllerShowErrors[keyof TechcorWebApiTasksControllerShowErrors];

export type TechcorWebApiTasksControllerShowResponses = {
  /**
   * Task
   */
  200: Task;
};

export type TechcorWebApiTasksControllerShowResponse =
  TechcorWebApiTasksControllerShowResponses[keyof TechcorWebApiTasksControllerShowResponses];

export type TechcorWebApiTasksControllerVerifyData = {
  body?: never;
  path: {
    /**
     * Organization slug
     */
    org_slug: string;
    /**
     * Project slug
     */
    project_slug: string;
    /**
     * Task ID
     */
    id: number;
  };
  query?: never;
  url: "/api/v1/{org_slug}/{project_slug}/tasks/{id}/verify";
};

export type TechcorWebApiTasksControllerVerifyErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * Not found
   */
  404: ErrorResponse;
};

export type TechcorWebApiTasksControllerVerifyError =
  TechcorWebApiTasksControllerVerifyErrors[keyof TechcorWebApiTasksControllerVerifyErrors];

export type TechcorWebApiTasksControllerVerifyResponses = {
  /**
   * Task
   */
  200: Task;
};

export type TechcorWebApiTasksControllerVerifyResponse =
  TechcorWebApiTasksControllerVerifyResponses[keyof TechcorWebApiTasksControllerVerifyResponses];
